# Generated by Django 4.2 on 2024-10-22 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='zapyty_o_dodaniu_w_przyjaciele',
            new_name='zapyty_o_przyjacielstwie',
        ),
    ]
