# Generated by Django 4.2 on 2024-10-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grupa',
            field=models.IntegerField(verbose_name='Grupa'),
        ),
        migrations.AlterField(
            model_name='user',
            name='klasa',
            field=models.IntegerField(verbose_name='Klasa'),
        ),
    ]
