# Generated by Django 4.2 on 2024-10-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_zapyty_o_dodaniu_w_przyjaciele_user_zapyty_o_przyjacielstwie_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='opis',
            field=models.TextField(default='Brak opisu', max_length=150, verbose_name='Opis'),
        ),
        migrations.AddField(
            model_name='user',
            name='o_sobie',
            field=models.TextField(default='Brak opisu', max_length=150, verbose_name='O sobie'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='ikona',
            field=models.ImageField(blank=True, default='default/default_chat.png', null=True, upload_to='chat_icons', verbose_name='Ikonka'),
        ),
    ]
