# Generated by Django 4.2 on 2024-10-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_grupa_alter_user_imie_alter_user_kierunek_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grupa',
            field=models.IntegerField(blank=True, null=True, verbose_name='Grupa'),
        ),
        migrations.AlterField(
            model_name='user',
            name='imie',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='user',
            name='kierunek',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Kierunek'),
        ),
        migrations.AlterField(
            model_name='user',
            name='klasa',
            field=models.IntegerField(blank=True, null=True, verbose_name='Klasa'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nazwisko',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nazwisko'),
        ),
    ]
