# Generated by Django 4.2 on 2024-10-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_chat_adminy'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='motyw',
            field=models.BooleanField(default=True, verbose_name='Motyw'),
        ),
    ]
