# Generated by Django 4.2 on 2024-10-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_grupa_alter_user_imie_alter_user_kierunek_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grupa',
            field=models.IntegerField(verbose_name='Grupa'),
        ),
        migrations.AlterField(
            model_name='user',
            name='imie',
            field=models.CharField(max_length=20, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='user',
            name='kierunek',
            field=models.CharField(max_length=2, verbose_name='Kierunek'),
        ),
        migrations.AlterField(
            model_name='user',
            name='klasa',
            field=models.IntegerField(verbose_name='Klasa'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nazwisko',
            field=models.CharField(max_length=30, verbose_name='Nazwisko'),
        ),
    ]
