# Generated by Django 4.2 on 2024-10-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_motyw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='opis',
            field=models.TextField(default='Brak opisu', max_length=400, verbose_name='Opis'),
        ),
    ]
