# Generated by Django 4.2 on 2024-10-13 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
        ('users', '0006_alter_user_grupa_alter_user_imie_alter_user_kierunek_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='czaty',
            field=models.JSONField(default='{[]}', verbose_name='Czaty'),
        ),
        migrations.AddField(
            model_name='user',
            name='ostatni_czat',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='chats.chat', verbose_name='Ostatni czat'),
        ),
        migrations.AddField(
            model_name='user',
            name='pryjaciole',
            field=models.JSONField(default='{[]}', verbose_name='Przyjaciole'),
        ),
    ]
