# Generated by Django 4.2 on 2024-10-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_chat_opis'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='czy_grupa',
            field=models.BooleanField(default=True, verbose_name='Czy grupa'),
        ),
    ]
