# Generated by Django 4.2 on 2024-10-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_czaty_user_ostatni_czat_user_pryjaciole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='czaty',
            field=models.JSONField(default={'c': []}, verbose_name='Czaty'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pryjaciole',
            field=models.JSONField(default={'w': []}, verbose_name='Przyjaciole'),
        ),
    ]
