# Generated by Django 4.2 on 2024-10-13 15:44

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_czaty_alter_user_pryjaciole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='czaty',
            field=models.JSONField(default=users.models.User.d, verbose_name='Czaty'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pryjaciole',
            field=models.JSONField(default=users.models.User.d, verbose_name='Przyjaciole'),
        ),
    ]
