# Generated by Django 4.2 on 2024-10-13 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_alter_chat_wiadomosci'),
        ('users', '0009_alter_user_czaty_alter_user_pryjaciole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ostatni_czat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chats.chat', verbose_name='Ostatni czat'),
        ),
    ]
