# Generated by Django 4.2 on 2024-10-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_ostatni_czat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ostatni_czat',
            field=models.CharField(default='', max_length=50, verbose_name='Ostatni czat'),
        ),
    ]
