# Generated by Django 4.2 on 2024-10-13 20:04

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_ostatni_czat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='czaty',
            field=models.JSONField(default=users.models.User.d, null=True, verbose_name='Czaty'),
        ),
        migrations.AlterField(
            model_name='user',
            name='grupa',
            field=models.IntegerField(null=True, verbose_name='Grupa'),
        ),
        migrations.AlterField(
            model_name='user',
            name='imie',
            field=models.CharField(max_length=20, null=True, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='user',
            name='kierunek',
            field=models.CharField(max_length=2, null=True, verbose_name='Kierunek'),
        ),
        migrations.AlterField(
            model_name='user',
            name='klasa',
            field=models.IntegerField(null=True, verbose_name='Klasa'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nazwisko',
            field=models.CharField(max_length=30, null=True, verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ostatni_czat',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='Ostatni czat'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pryjaciole',
            field=models.JSONField(default=users.models.User.d, null=True, verbose_name='Przyjaciole'),
        ),
    ]
