# Generated by Django 4.2 on 2024-10-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rename_pryjaciole_user_przyjaciole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='static/img/default_avatar.png', null=True, upload_to='media/user_avatars', verbose_name='Avatar'),
        ),
    ]
