# Generated by Django 4.2 on 2024-10-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50, verbose_name='Nazwa')),
                ('icon', models.ImageField(upload_to='media/chat_icons', verbose_name='Ikonka')),
                ('wiadomosci', models.JSONField(default='{[]}', verbose_name='Wiadomości')),
            ],
            options={
                'verbose_name': 'Czat',
                'verbose_name_plural': 'Czaty',
                'db_table': 'chats.Chat',
            },
        ),
    ]
