# Generated by Django 4.2 on 2024-10-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='wiadomosci',
            field=models.JSONField(default={'w': []}, verbose_name='Wiadomości'),
        ),
    ]
