# Generated by Django 4.2 on 2024-10-13 15:44

import chats.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_chat_wiadomosci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='wiadomosci',
            field=models.JSONField(default=chats.models.Chat.d, verbose_name='Wiadomości'),
        ),
    ]
